using Microsoft.Extensions.Logging.Abstractions;
using MLoop.Core.Preprocessing.Incremental.RuleDiscovery.Models;
using MLoop.Core.Preprocessing.Incremental.ScriptGeneration;
using MLoop.Core.Preprocessing.Incremental.ScriptGeneration.Models;

namespace MLoop.Core.Tests.Preprocessing.Incremental.ScriptGeneration;

public class ScriptGeneratorTests : IDisposable
{
    private readonly ScriptGenerator _generator;
    private readonly string _tempDir;

    public ScriptGeneratorTests()
    {
        _generator = new ScriptGenerator(NullLogger<ScriptGenerator>.Instance);
        _tempDir = Path.Combine(Path.GetTempPath(), $"mloop-scriptgen-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        if (Directory.Exists(_tempDir))
            Directory.Delete(_tempDir, true);
    }

    private static PreprocessingRule CreateRule(
        string id = "rule-1",
        PreprocessingRuleType type = PreprocessingRuleType.MissingValueStrategy,
        string[] columnNames = null!)
    {
        return new PreprocessingRule
        {
            Id = id,
            Type = type,
            ColumnNames = columnNames ?? new[] { "Col1" },
            Description = $"Test rule {id}",
            PatternType = PatternType.MissingValue,
            RequiresHITL = false,
            Priority = 5,
            DiscoveredInStage = 1
        };
    }

    #region GenerateScript Tests

    [Fact]
    public void GenerateScript_EmptyRules_GeneratesValidScript()
    {
        var rules = Array.Empty<PreprocessingRule>();

        var script = _generator.GenerateScript(rules);

        Assert.Contains("namespace", script);
        Assert.Contains("class", script);
        Assert.Contains("Apply", script);
        Assert.Contains("return data;", script);
    }

    [Fact]
    public void GenerateScript_DefaultOptions_ContainsAutoGeneratedHeader()
    {
        var rules = new[] { CreateRule() };

        var script = _generator.GenerateScript(rules);

        Assert.Contains("<auto-generated>", script);
        Assert.Contains("</auto-generated>", script);
    }

    [Fact]
    public void GenerateScript_NoComments_OmitsHeader()
    {
        var rules = new[] { CreateRule() };
        var options = new ScriptGenerationOptions { IncludeComments = false };

        var script = _generator.GenerateScript(rules, options);

        Assert.DoesNotContain("<auto-generated>", script);
        Assert.DoesNotContain("/// <summary>", script);
    }

    [Fact]
    public void GenerateScript_CustomNamespace_UsesNamespace()
    {
        var rules = new[] { CreateRule() };
        var options = new ScriptGenerationOptions { Namespace = "My.Custom.Namespace" };

        var script = _generator.GenerateScript(rules, options);

        Assert.Contains("namespace My.Custom.Namespace;", script);
    }

    [Fact]
    public void GenerateScript_CustomClassName_UsesClassName()
    {
        var rules = new[] { CreateRule() };
        var options = new ScriptGenerationOptions { ClassName = "MyProcessor" };

        var script = _generator.GenerateScript(rules, options);

        Assert.Contains("class MyProcessor", script);
    }

    [Fact]
    public void GenerateScript_SealedClass_ContainsSealed()
    {
        var rules = new[] { CreateRule() };
        var options = new ScriptGenerationOptions { SealedClass = true };

        var script = _generator.GenerateScript(rules, options);

        Assert.Contains("sealed class", script);
    }

    [Fact]
    public void GenerateScript_NotSealed_NoSealedKeyword()
    {
        var rules = new[] { CreateRule() };
        var options = new ScriptGenerationOptions { SealedClass = false };

        var script = _generator.GenerateScript(rules, options);

        Assert.DoesNotContain("sealed class", script);
        Assert.Contains("public class", script);
    }

    [Fact]
    public void GenerateScript_WithLogging_IncludesLoggerField()
    {
        var rules = new[] { CreateRule() };
        var options = new ScriptGenerationOptions { IncludeLogging = true };

        var script = _generator.GenerateScript(rules, options);

        Assert.Contains("using Microsoft.Extensions.Logging;", script);
        Assert.Contains("ILogger _logger", script);
    }

    [Fact]
    public void GenerateScript_WithValidation_IncludesNullCheck()
    {
        var rules = new[] { CreateRule() };
        var options = new ScriptGenerationOptions { IncludeValidation = true };

        var script = _generator.GenerateScript(rules, options);

        Assert.Contains("ArgumentNullException", script);
    }

    [Fact]
    public void GenerateScript_NoValidation_OmitsNullCheck()
    {
        var rules = new[] { CreateRule() };
        var options = new ScriptGenerationOptions { IncludeValidation = false };

        var script = _generator.GenerateScript(rules, options);

        Assert.DoesNotContain("ArgumentNullException", script);
    }

    [Fact]
    public void GenerateScript_AsyncMode_UsesAsyncKeywords()
    {
        var rules = new[] { CreateRule() };
        var options = new ScriptGenerationOptions { GenerateAsync = true };

        var script = _generator.GenerateScript(rules, options);

        Assert.Contains("async Task<DataFrame>", script);
        Assert.Contains("await ", script);
    }

    [Fact]
    public void GenerateScript_SyncMode_NoAsyncKeywords()
    {
        var rules = new[] { CreateRule() };
        var options = new ScriptGenerationOptions { GenerateAsync = false };

        var script = _generator.GenerateScript(rules, options);

        Assert.Contains("DataFrame Apply(", script);
        Assert.DoesNotContain("async Task<DataFrame>", script);
    }

    [Fact]
    public void GenerateScript_MultipleRules_GeneratesAllHelperMethods()
    {
        var rules = new[]
        {
            CreateRule("r1", PreprocessingRuleType.MissingValueStrategy, new[] { "Col1" }),
            CreateRule("r2", PreprocessingRuleType.OutlierHandling, new[] { "Col2" }),
            CreateRule("r3", PreprocessingRuleType.WhitespaceNormalization, new[] { "Col3" })
        };

        var script = _generator.GenerateScript(rules);

        Assert.Contains("ApplyMissingValueStrategy_Col1_0", script);
        Assert.Contains("ApplyOutlierHandling_Col2_1", script);
        Assert.Contains("ApplyWhitespaceNormalization_Col3_2", script);
    }

    [Theory]
    [InlineData(PreprocessingRuleType.MissingValueStrategy, "missing value")]
    [InlineData(PreprocessingRuleType.OutlierHandling, "outlier")]
    [InlineData(PreprocessingRuleType.WhitespaceNormalization, "whitespace")]
    [InlineData(PreprocessingRuleType.DateFormatStandardization, "date format")]
    [InlineData(PreprocessingRuleType.CategoryMapping, "category")]
    [InlineData(PreprocessingRuleType.TypeConversion, "type conversion")]
    public void GenerateScript_EachRuleType_GeneratesPlaceholderCode(
        PreprocessingRuleType type, string expectedKeyword)
    {
        var rules = new[] { CreateRule(type: type) };

        var script = _generator.GenerateScript(rules);

        Assert.Contains(expectedKeyword, script, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void GenerateScript_UnhandledRuleType_GeneratesTodo()
    {
        var rules = new[] { CreateRule(type: PreprocessingRuleType.BusinessLogicDecision) };

        var script = _generator.GenerateScript(rules);

        Assert.Contains("TODO", script);
    }

    [Fact]
    public void GenerateScript_IncludesDataFrameUsing()
    {
        var rules = Array.Empty<PreprocessingRule>();

        var script = _generator.GenerateScript(rules);

        Assert.Contains("using Microsoft.Data.Analysis;", script);
    }

    [Fact]
    public void GenerateScript_NullOptions_UsesDefaults()
    {
        var rules = new[] { CreateRule() };

        var script = _generator.GenerateScript(rules, null);

        Assert.Contains("namespace MLoop.Generated;", script);
        Assert.Contains("PreprocessingScript", script);
    }

    #endregion

    #region SaveScriptAsync Tests

    [Fact]
    public async Task SaveScriptAsync_CreatesFile()
    {
        var path = Path.Combine(_tempDir, "test.cs");

        await _generator.SaveScriptAsync("// test", path);

        Assert.True(File.Exists(path));
        Assert.Equal("// test", await File.ReadAllTextAsync(path));
    }

    [Fact]
    public async Task SaveScriptAsync_CreatesDirectory()
    {
        var path = Path.Combine(_tempDir, "sub", "dir", "test.cs");

        await _generator.SaveScriptAsync("// test", path);

        Assert.True(File.Exists(path));
    }

    #endregion

    #region GenerateAndSaveAsync Tests

    [Fact]
    public async Task GenerateAndSaveAsync_CreatesScriptFile()
    {
        var rules = new[] { CreateRule() };
        var path = Path.Combine(_tempDir, "output.cs");

        await _generator.GenerateAndSaveAsync(rules, path);

        Assert.True(File.Exists(path));
        var content = await File.ReadAllTextAsync(path);
        Assert.Contains("class PreprocessingScript", content);
    }

    #endregion
}
