using System.CommandLine;
using MLoop.CLI.Infrastructure.FileSystem;
using Spectre.Console;

namespace MLoop.CLI.Commands;

/// <summary>
/// Docker command to generate containerization files
/// </summary>
public static class DockerCommand
{
    public static Command Create()
    {
        var command = new Command("docker", "Generate Docker configuration for model deployment");

        var modelNameOption = new Option<string?>("--name", "-n")
        {
            Description = "Model name to containerize (defaults to 'default')"
        };

        var portOption = new Option<int>("--port", "-p")
        {
            Description = "Exposed port for API",
            DefaultValueFactory = _ => 5000
        };

        command.Options.Add(modelNameOption);
        command.Options.Add(portOption);

        command.SetAction((parseResult) =>
        {
            var modelName = parseResult.GetValue(modelNameOption) ?? "default";
            var port = parseResult.GetValue(portOption);
            return ExecuteAsync(modelName, port);
        });

        return command;
    }

    private static async Task<int> ExecuteAsync(string modelName, int port)
    {
        try
        {
            var fileSystem = new FileSystemManager();
            var projectDiscovery = new ProjectDiscovery(fileSystem);

            // Verify we're in an MLoop project
            string projectRoot;
            try
            {
                projectRoot = projectDiscovery.FindRoot();
            }
            catch (InvalidOperationException)
            {
                AnsiConsole.MarkupLine("[red]Error:[/] Not inside a MLoop project.");
                AnsiConsole.MarkupLine("Run [blue]mloop init[/] to create a new project.");
                return 1;
            }

            AnsiConsole.WriteLine();
            AnsiConsole.Write(new Rule("[blue]Docker Configuration Generator[/]").LeftJustified());
            AnsiConsole.WriteLine();

            // Generate Dockerfile
            var dockerfilePath = Path.Combine(projectRoot, "Dockerfile");
            var dockerfileContent = GenerateDockerfile(modelName, port);
            await File.WriteAllTextAsync(dockerfilePath, dockerfileContent);

            AnsiConsole.MarkupLine($"[green]✓[/] Generated: [cyan]{dockerfilePath}[/]");

            // Generate .dockerignore
            var dockerignorePath = Path.Combine(projectRoot, ".dockerignore");
            var dockerignoreContent = GenerateDockerignore();
            await File.WriteAllTextAsync(dockerignorePath, dockerignoreContent);

            AnsiConsole.MarkupLine($"[green]✓[/] Generated: [cyan]{dockerignorePath}[/]");

            // Generate docker-compose.yml
            var composePath = Path.Combine(projectRoot, "docker-compose.yml");
            var composeContent = GenerateDockerCompose(modelName, port);
            await File.WriteAllTextAsync(composePath, composeContent);

            AnsiConsole.MarkupLine($"[green]✓[/] Generated: [cyan]{composePath}[/]");

            // Display usage instructions
            AnsiConsole.WriteLine();
            AnsiConsole.Write(new Rule("[yellow]Usage Instructions[/]").LeftJustified());
            AnsiConsole.WriteLine();

            AnsiConsole.MarkupLine("[bold]Build Docker image:[/]");
            AnsiConsole.MarkupLine($"  docker build -t mloop-{modelName}:latest .");
            AnsiConsole.WriteLine();

            AnsiConsole.MarkupLine("[bold]Run container:[/]");
            AnsiConsole.MarkupLine($"  docker run -p {port}:{port} mloop-{modelName}:latest");
            AnsiConsole.WriteLine();

            AnsiConsole.MarkupLine("[bold]Or use docker-compose:[/]");
            AnsiConsole.MarkupLine("  docker-compose up");
            AnsiConsole.WriteLine();

            AnsiConsole.MarkupLine("[bold]Test API:[/]");
            AnsiConsole.MarkupLine($"  curl http://localhost:{port}/health");
            AnsiConsole.WriteLine();

            return 0;
        }
        catch (Exception ex)
        {
            AnsiConsole.Markup("[red]Error:[/] ");
            AnsiConsole.WriteLine(ex.Message);
            return 1;
        }
    }

    private static string GenerateDockerfile(string modelName, int port)
    {
        return $@"# MLoop Model Serving Dockerfile
# Auto-generated by 'mloop docker'

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
WORKDIR /app
EXPOSE {port}

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Copy project files
COPY mloop.yaml ./
COPY .mloop/ ./.mloop/

# Install MLoop CLI globally
RUN dotnet tool install --global mloop --version *

# Set PATH to include .NET tools
ENV PATH=""$PATH:/root/.dotnet/tools""

# Production stage
FROM base AS final
WORKDIR /app

# Copy model artifacts
COPY --from=build /src/.mloop ./.mloop
COPY --from=build /src/mloop.yaml ./

# Install MLoop CLI and dependencies
RUN apt-get update && \
    apt-get install -y wget && \
    wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    rm packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y dotnet-sdk-10.0 && \
    dotnet tool install --global mloop --version * && \
    apt-get clean

ENV PATH=""$PATH:/root/.dotnet/tools""

# Set environment variables
ENV ASPNETCORE_URLS=http://+:{port}
ENV MLOOP_PROJECT_ROOT=/app
ENV MLOOP_MODEL_NAME={modelName}

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD wget --quiet --tries=1 --spider http://localhost:{port}/health || exit 1

# Start the API server
ENTRYPOINT [""mloop"", ""serve""]
CMD [""--host"", ""0.0.0.0"", ""--port"", ""{port}""]
";
    }

    private static string GenerateDockerignore()
    {
        return @"# MLoop Docker Ignore
# Auto-generated by 'mloop docker'

# Ignore temp files
.mloop/temp/
*.tmp

# Ignore logs
*.log

# Ignore OS files
.DS_Store
Thumbs.db

# Ignore IDE files
.vs/
.vscode/
.idea/
*.swp
*.swo

# Ignore git
.git/
.gitignore

# Ignore Docker files
Dockerfile
docker-compose.yml
.dockerignore

# Ignore build artifacts (keep models)
bin/
obj/
!.mloop/models/
";
    }

    private static string GenerateDockerCompose(string modelName, int port)
    {
        return $@"# MLoop Docker Compose Configuration
# Auto-generated by 'mloop docker'

version: '3.8'

services:
  mloop-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mloop-{modelName}:latest
    container_name: mloop-{modelName}
    ports:
      - ""{port}:{port}""
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MLOOP_MODEL_NAME={modelName}
    volumes:
      - ./.mloop/models:/app/.mloop/models:ro  # Read-only model access
    restart: unless-stopped
    healthcheck:
      test: [""CMD"", ""wget"", ""--quiet"", ""--tries=1"", ""--spider"", ""http://localhost:{port}/health""]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Optional: nginx reverse proxy
  # nginx:
  #   image: nginx:alpine
  #   container_name: mloop-nginx
  #   ports:
  #     - ""80:80""
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - mloop-api
  #   restart: unless-stopped
";
    }
}
