using MLoop.Core.DataQuality;
using MLoop.Extensibility.Preprocessing;

namespace MLoop.Core.Tests.DataQuality;

public class PreprocessingScriptGeneratorTests : IDisposable
{
    private readonly PreprocessingScriptGenerator _generator;
    private readonly string _tempDir;

    public PreprocessingScriptGeneratorTests()
    {
        _generator = new PreprocessingScriptGenerator(new TestLogger());
        _tempDir = Path.Combine(Path.GetTempPath(), "mloop-psg-tests", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        if (Directory.Exists(_tempDir))
            Directory.Delete(_tempDir, true);
    }

    #region GenerateScript - Basic Structure

    [Fact]
    public void GenerateScript_EmptyIssues_GeneratesValidStructure()
    {
        var script = _generator.GenerateScript(new List<DataQualityIssue>());

        Assert.Contains("public class AutoGeneratedPreprocessingScript : IPreprocessingScript", script);
        Assert.Contains("ExecuteAsync", script);
        Assert.Contains("PreprocessingResult", script);
    }

    [Fact]
    public void GenerateScript_CustomName_UsesProvidedName()
    {
        var script = _generator.GenerateScript(new List<DataQualityIssue>(), "MyCustomScript");

        Assert.Contains("public class MyCustomScript : IPreprocessingScript", script);
    }

    [Fact]
    public void GenerateScript_NoIssues_GeneratesPassThrough()
    {
        var script = _generator.GenerateScript(new List<DataQualityIssue>());

        Assert.Contains("No critical issues detected, pass through", script);
    }

    #endregion

    #region GenerateScript - Encoding Issues

    [Fact]
    public void GenerateScript_EncodingIssue_GeneratesEncodingFix()
    {
        var issues = new List<DataQualityIssue>
        {
            new()
            {
                Type = DataQualityIssueType.EncodingIssue,
                Severity = IssueSeverity.High,
                Description = "File uses non-UTF-8 encoding"
            }
        };

        var script = _generator.GenerateScript(issues);

        Assert.Contains("Fix encoding issues", script);
        Assert.Contains("DetectEncodingAsync", script);
        Assert.Contains("UTF8Encoding", script);
    }

    #endregion

    #region GenerateScript - Duplicate Rows

    [Fact]
    public void GenerateScript_DuplicateRows_GeneratesDedup()
    {
        var issues = new List<DataQualityIssue>
        {
            new()
            {
                Type = DataQualityIssueType.DuplicateRows,
                Severity = IssueSeverity.High,
                Description = "10% duplicate rows detected"
            }
        };

        var script = _generator.GenerateScript(issues);

        Assert.Contains("Remove duplicates", script);
        Assert.Contains("Distinct()", script);
    }

    #endregion

    #region GenerateScript - Whitespace Issues

    [Fact]
    public void GenerateScript_WhitespaceIssues_GeneratesTrim()
    {
        var issues = new List<DataQualityIssue>
        {
            new()
            {
                Type = DataQualityIssueType.WhitespaceIssues,
                Severity = IssueSeverity.High,
                Description = "Leading/trailing whitespace detected"
            }
        };

        var script = _generator.GenerateScript(issues);

        Assert.Contains("Trim whitespace", script);
        Assert.Contains("Trim()", script);
    }

    #endregion

    #region GenerateScript - Combined Issues

    [Fact]
    public void GenerateScript_MultipleIssues_GeneratesAllFixes()
    {
        var issues = new List<DataQualityIssue>
        {
            new()
            {
                Type = DataQualityIssueType.EncodingIssue,
                Severity = IssueSeverity.Critical,
                Description = "Non-UTF-8 encoding"
            },
            new()
            {
                Type = DataQualityIssueType.DuplicateRows,
                Severity = IssueSeverity.High,
                Description = "Duplicate rows"
            },
            new()
            {
                Type = DataQualityIssueType.WhitespaceIssues,
                Severity = IssueSeverity.High,
                Description = "Whitespace issues"
            }
        };

        var script = _generator.GenerateScript(issues);

        Assert.Contains("Fix encoding issues", script);
        Assert.Contains("Remove duplicates", script);
        Assert.Contains("Trim whitespace", script);
        Assert.Contains("DetectEncodingAsync", script);
    }

    [Fact]
    public void GenerateScript_OnlyLowSeverityIssues_OmitsFromComments()
    {
        var issues = new List<DataQualityIssue>
        {
            new()
            {
                Type = DataQualityIssueType.DuplicateRows,
                Severity = IssueSeverity.Low,
                Description = "Minor duplicates"
            }
        };

        var script = _generator.GenerateScript(issues);

        // Low severity issues should not appear in the summary comments
        Assert.DoesNotContain("Minor duplicates", script);
        // But the fix should still be generated
        Assert.Contains("Remove duplicates", script);
    }

    #endregion

    #region GenerateScript - Issue Count in Output

    [Fact]
    public void GenerateScript_IncludesIssueCount()
    {
        var issues = new List<DataQualityIssue>
        {
            new()
            {
                Type = DataQualityIssueType.DuplicateRows,
                Severity = IssueSeverity.High,
                Description = "Duplicates found"
            },
            new()
            {
                Type = DataQualityIssueType.WhitespaceIssues,
                Severity = IssueSeverity.High,
                Description = "Whitespace"
            }
        };

        var script = _generator.GenerateScript(issues);

        Assert.Contains("Fixed 2 data quality issue(s)", script);
    }

    #endregion

    #region SaveScriptAsync

    [Fact]
    public async Task SaveScriptAsync_CreatesFile()
    {
        var outputPath = Path.Combine(_tempDir, "test_script.cs");

        await _generator.SaveScriptAsync("// test content", outputPath);

        Assert.True(File.Exists(outputPath));
        Assert.Equal("// test content", await File.ReadAllTextAsync(outputPath));
    }

    [Fact]
    public async Task SaveScriptAsync_CreatesNestedDirectories()
    {
        var outputPath = Path.Combine(_tempDir, "sub", "dir", "test_script.cs");

        await _generator.SaveScriptAsync("// content", outputPath);

        Assert.True(File.Exists(outputPath));
    }

    #endregion

    private class TestLogger : ILogger
    {
        public void Debug(string message) { }
        public void Info(string message) { }
        public void Warning(string message) { }
        public void Error(string message) { }
        public void Error(string message, Exception exception) { }
    }
}
